#!/usr/bin/env bash
#
# The idea is to check whether the version number has been incremented,
# and if so, aws s3 cp --recursive the static assets to a new version number
#
# TODO figure out when to prompt about deleting old ones?

set -eu
# set -x

DEFAULT_BRANCH_NAME=main
NAME=astro_pi_replay
VERSION_FILE="src/${NAME}/__init__.py"
BRANCH=$(git branch --show-current)
S3_BUCKET="s3://static.raspberrypi.org/files/astro-pi/$NAME"


echo "Starting pre-push checks..."

extract_version() {
  # Returns the version number of the Python package
  # extracted from src/astro_pi_replay/__init__.py.
  #
  # $1 - The commit hash to use to fetch the contents of
  #      src/astro_pi_replay/__init__.py.
  git show "$1":"$VERSION_FILE" | \
    grep "__version__" | \
    sed 's/^__version__\s*=\s*"\?\([0-9.]\+\)\"\?$/\1/g'
}

semver_gt() {
  # Returns 1 when the first argument is a greater version than
  # the second, otherwise returns 0.
  #
  # $1 - A semantic version of the form 'A.B.C'.
  # $2 - A semantic version of the form 'A.B.C'.
  mapfile -d "." -t arr1 < <(echo "$1" | tr -d "\n")
  mapfile -d "." -t arr2 < <(echo "$2" | tr -d "\n")

  local is_gt=0
  for ((i = 0; i < ${#arr1[@]}; i++)); do
    if [ "${arr1[i]}" -gt "${arr2[i]}" ]; then
      is_gt=1
      echo "1"
      break
    fi
  done
  [ "$is_gt" -ne 1 ] && echo "0"
  unset arr1
  unset arr2
}

semver_eq() {
  # Returns 1 when the first argument is equal to the second.
  # Otherwise returns 0.
  #
  # $1 - A semantic version of the form 'A.B.C'.
  # $2 - A semantic version of the form 'A.B.C'.
  mapfile -d "." -t arr1 < <(echo "$1" | tr -d "\n")
  mapfile -d "." -t arr2 < <(echo "$2" | tr -d "\n")

  local is_eq=0
  for ((i = 0; i < ${#arr1[@]}; i++)); do
    if [ "${arr1[i]}" -eq "${arr2[i]}" ]; then
      is_eq=1
      echo "1"
      break
    fi
  done
  [ "$is_eq" -ne 1 ] && echo "0"
  unset arr1
  unset arr2
}

semver_lt() {
  # Returns 1 when the first argument is less than the second.
  # Otherwise returns 0.
  #
  # $1 - A semantic version of the form 'A.B.C'.
  # $2 - A semantic version of the form 'A.B.C'.
  mapfile -d "." -t arr1 < <(echo "$1" | tr -d "\n")
  mapfile -d "." -t arr2 < <(echo "$2" | tr -d "\n")

  local is_lt=0
  for ((i = 0; i < ${#arr1[@]}; i++)); do
    if [ "${arr1[i]}" -eq "${arr2[i]}" ]; then
      is_lt=1
      echo "1"
      break
    fi
  done
  [ "$is_lt" -ne 1 ] && echo "0"
  unset arr1
  unset arr2
}


# 1. Check if there is a remote branch already for this branch
remote_branch=$(git ls-remote --heads origin "refs/heads/$BRANCH")

if [ -z "$remote_branch" ]; then
  # no remote branch already - use DEFAULT_BRANCH_NAME? TODO
  remote_branch=$(git ls-remote --heads origin "refs/heads/$DEFAULT_BRANCH_NAME")
fi

# shellcheck disable=SC2001
remote_hash=$(echo "$remote_branch" | sed 's/\([a-f0-9]\+\)\s\+.\+/\1/g')
current_hash=$(git rev-parse HEAD)

if [ "$remote_hash" = "$current_hash" ]; then
  # Nothing to be done as the commit hashes are the same
  exit 0
fi

# Check if Python package version has been changed"
remote_version=$(extract_version "$remote_hash")
current_version=$(extract_version "$current_hash")

if [ "$(semver_gt "$current_version" "$remote_version")" -ne 1 ]; then
  echo "No version change detected"
  exit 0
fi

# Check s3 for current_version
result=$(aws s3 ls "$S3_BUCKET/$current_version" || echo "")
if [ -n "$result" ]; then
  # assets are already in S3"
  exit 0
fi

# Find the latest (largest) version in aws
latest_version=$(aws s3 ls "$S3_BUCKET/" | \
  sed 's/.\+PRE \([0-9.]\+\)\//\1/g' | sort -Vr | \
  head -n 1)

if [ "$(semver_eq "$remote_version" "$latest_version")" -ne 1 ]; then
  printf "\tAssets not found in S3. Please copy them using:\n"
  printf "\taws s3 cp --recursive %s/%s %s/%s\n" "$S3_BUCKET" "$latest_version" "$S3_BUCKET" "$current_version"
  printf "\tor\n"
  printf "\taws s3 cp --recursive %s/%s %s/%s\n" "$S3_BUCKET" "$remote_version" "$S3_BUCKET" "$current_version"
  exit 1
else
  printf "\tUploading assets\n"
  aws s3 cp --recursive "${S3_BUCKET}/${remote_version}" "${S3_BUCKET}/${current_version}"
fi
exit 0
