[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "astro_pi_executor"
description = "A CLI to execute Mission Space Lab experiments for 2023-2024."
dynamic = ["version"]
authors = [
  { name="Geraint Ballinger", email="geraint.ballinger@raspberrypi.org" }
]
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]
dependencies = [
  "colorzero >= 2.0",
  "pandas == 2.0.3",
  "Pillow >= 10.0.0",
  "requests >= 2.31",
  "skyfield >= 1.46",
  "typing_extensions >= 4.7.1",
  "tqdm >= 4.66.0",
  "scipy >= 1.11.2",
  "exif >= 1.6.0",
]

[project.scripts]
astro_pi_executor = "astro_pi_executor.main:main"

[project.urls]
Homepage = "https://github.com/astro-pi/astro_pi_executor"

[tool.setuptools.dynamic]
version = {attr = "astro_pi_executor.__init__.__version__"}

[tool.isort]
atomic = true
line_length = 88
profile = "black"
skip_gitignore = true
src_paths = ["src", "test"]
skip_glob = ["test/resources", "venv"]

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
(
  ^/test/resources
)
'''

[tool.bandit]
skips = ["B101", "B404"]
exclude = ["test/resources"]

