[pytest]
pythonpath = src
; Uncomment the below to emit debug logs declaratively
; Otherwise, execute pytest with -o log_cli=true --log-cli-level=DEBUG flags
; log_cli_level = DEBUG
; log_cli = true

