FROM astro_pi_replay:latest-base

ARG DOCKER_USER=""
ARG DOCKER_UID=1000
ARG DOCKER_GID=1000

RUN /opt/${NAME}/${VENV_NAME}/bin/Astro-Pi-Replay download --sequence mz_synthetic_test_data

# if DOCKER_USER is set, use it and given uid/gids.
RUN if [ "$DOCKER_USER" -n ]; then \
  useradd ${DOCKER_USER} -m \
    -g ${DOCKER_GID} \
    -u ${DOCKER_UID} \
fi
